# Site settings
title: OSSOS - the Outer Solar System Origins Survey
email: ossoscore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A survey of the sky using MegaCam on the 3.6-metre Canada-France-Hawaii Telescope.
  We aim to discover several hundred distant icy worlds at the edge of our Solar System.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.ossos-survey.org" # the base hostname & protocol for your site
twitter_username: OSSOSurvey
# github_username:  OSSOS

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
